#ifndef SHOOT_HEAT_CONFIG_H
#define SHOOT_HEAT_CONFIG_H
//0 1 2 分别是3v3的爆发优先和冷却优先 以及步兵挑战模式的热量参数配置
#define SHOOT_HEAT_MODE_BURST 0
#define SHOOT_HEAT_MODE_COOLING 1
#define SHOOT_HEAT_MODE_INFANTRY_CHALLENGE 2

#ifndef SHOOT_HEAT_MODE
#define SHOOT_HEAT_MODE SHOOT_HEAT_MODE_BURST
#endif

#if SHOOT_HEAT_MODE == SHOOT_HEAT_MODE_BURST
#define SHOOT_HEAT_LIMIT 230.0f
#define SHOOT_HEAT_COOLDOWN_PER_S 7.0f
#elif SHOOT_HEAT_MODE == SHOOT_HEAT_MODE_COOLING
#define SHOOT_HEAT_LIMIT 88.0f
#define SHOOT_HEAT_COOLDOWN_PER_S 24.0f
#elif SHOOT_HEAT_MODE == SHOOT_HEAT_MODE_INFANTRY_CHALLENGE
#define SHOOT_HEAT_LIMIT 80.0f
#define SHOOT_HEAT_COOLDOWN_PER_S 4.85f
#else
#error "Invalid SHOOT_HEAT_MODE"
#endif

#endif
